package com.example.quickbooksimporter.domain;

public enum AppJobType {
    IMPORT_PREVIEW,
    BATCH_VALIDATION,
    QBO_CLEANUP_SEARCH,
    QBO_CLEANUP_DELETE,
    QBO_CLEANUP_VOID,
    QBO_CLEANUP_RECOVERY_PLAN,
    QBO_CLEANUP_RECOVERY_EXECUTION,
    RECONCILIATION_PREVIEW,
    RECONCILIATION_APPLY,
    SETTINGS_LOAD_INCOME_ACCOUNTS
}
