spring.application.name=quickbooks-importer
server.port=${PORT:8090}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/quickbooks_importer}
spring.datasource.username=${DB_USERNAME:mhcybroot}
spring.datasource.password=${DB_PASSWORD:MhR@2025}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

vaadin.launch-browser=true

app.security.username=${APP_USERNAME:admin}
app.security.password=${APP_PASSWORD:admin123}

app.quickbooks.client-id=${QB_CLIENT_ID:ABaJ2SoyIcgpTVb1iq0oAipB7vSVrc5blFhgAYqYnlV3P0lu2f}
app.quickbooks.client-secret=${QB_CLIENT_SECRET:2Td647asASBEbawVExOK6KhUdj5oFmJ67kAW9USo}
app.quickbooks.redirect-uri=${QB_REDIRECT_URI:http://localhost:8080/oauth/quickbooks/callback}
app.quickbooks.base-url=${QB_BASE_URL:https://sandbox-quickbooks.api.intuit.com}
app.quickbooks.authorization-url=${QB_AUTH_URL:https://appcenter.intuit.com/connect/oauth2}
app.quickbooks.token-url=${QB_TOKEN_URL:https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer}
app.quickbooks.scopes=com.intuit.quickbooks.accounting
app.quickbooks.environment=${QB_ENVIRONMENT:sandbox}
app.quickbooks.service-item-income-account-id=${QB_SERVICE_ITEM_INCOME_ACCOUNT_ID:1}
